"""empty message

Revision ID: 8524cda9645a
Revises: 
Create Date: 2018-05-21 16:01:23.805335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8524cda9645a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BBQ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Enum('standard', 'superior', 'deluxe', name='quality'), nullable=True),
    sa.Column('instock', sa.Boolean(), nullable=True),
    sa.Column('package', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('BBQ')
    # ### end Alembic commands ###
